# Generated by Django 4.0.1 on 2022-08-17 04:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('marks_10', models.DecimalField(decimal_places=1, max_digits=5)),
                ('marks_12', models.DecimalField(decimal_places=1, max_digits=5)),
                ('marks_degree', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_teacher', models.BooleanField()),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=30)),
                ('isSeen', models.BooleanField(default=False)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), size=None)),
                ('uploadedBy', models.CharField(max_length=30)),
                ('verifiedBy', models.CharField(max_length=30)),
                ('answer', models.CharField(max_length=75)),
                ('Class', models.CharField(max_length=20)),
                ('isRendered', models.BooleanField(default=False)),
                ('isRenderedat', models.DateTimeField(blank=True, null=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('encodedValue', models.CharField(max_length=30)),
                ('difficulty', models.IntegerField()),
                ('subject', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('noOfTimesFaved', models.IntegerField(default=0)),
                ('explanation', models.TextField(default='No explanation')),
                ('COLevel', models.CharField(default='Understand', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=30)),
                ('favourites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=[], size=None)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isVerifier', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Verifier',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='basic.user')),
                ('questionsVerified', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('expertise', models.TextField()),
            ],
        ),
    ]
