# Generated by Django 4.0.1 on 2022-08-18 18:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_question_uploadedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favourites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
