# Generated by Django 4.0.1 on 2022-08-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_alter_userprofile_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='email',
            field=models.CharField(default='hello@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
