# Generated by Django 4.0.1 on 2022-08-19 08:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_applications_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='expertise',
            field=models.CharField(default='ok', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verifier',
            name='questionsVerified',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
