# Generated by Django 4.0.1 on 2022-08-20 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_applications_expertise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='verifynotif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='verifiedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
