# Generated by Django 4.0.1 on 2022-08-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_notifications_createdat_notifications_verifynotif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifier',
            name='email',
            field=models.CharField(default='geju.2002@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verifier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
