# Generated by Django 4.0.1 on 2022-08-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_verifier_email_alter_verifier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='quesid',
            field=models.IntegerField(blank=True),
        ),
    ]
