# Generated by Django 4.0.1 on 2022-08-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_alter_notifications_quesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='quesid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
