# Generated by Django 4.0.1 on 2022-08-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_alter_notifications_quesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='encodedValue',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='uploadedBy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='verifiedBy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
