# Generated by Django 4.0.1 on 2022-08-23 06:07

from django.db import migrations
import ndarraydjango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_alter_question_encodedvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='encodedValue',
            field=ndarraydjango.fields.NDArrayField(blank=True, editable=True, null=True, shape=(1, 768)),
        ),
    ]
