# Generated by Django 4.0.1 on 2022-08-23 07:13

from django.db import migrations, models
import ndarraydjango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_alter_question_encodedvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='encoded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encodedValue', ndarraydjango.fields.NDArrayField(blank=True, editable=True, null=True, shape=(1, 768))),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='encodedValue',
        ),
    ]
